### ISSUE TITLE
can not withdraw rewards ki-desktop-wallet v0.4.0

### ISSUE THREAD

**Issue by godas14** [KiFoundation/ki-desktop-wallet#40]
When I sign withdraw rewards I can see down side Transaction sent with success
But in fact no withdraw coming to my account
Withdraw no working
What I have to do?

**Comment by dkrm0** [comment]
Hi @godas14, I've the exact same problem. How did you fix it?

**Comment by godas14** [comment]
Hi, I didn’t have enough coins for gas. I just added some coins and problem gone away
